//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HooshBartarAccountingApp.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRooznameh
    {
        public long Id { get; set; }
        public decimal SanadId { get; set; }
        public System.DateTime SanadTarikhMiladi { get; set; }
        public string SanadTarikhShamsi { get; set; }
        public string SanadTozih { get; set; }
        public Nullable<long> SanadBedehkar { get; set; }
        public Nullable<long> SabadBestankar { get; set; }
        public string NameHesab { get; set; }
        public string NameGroupHesab { get; set; }
        public string NameSumGroupHesab { get; set; }
        public long IdHesab { get; set; }
        public string BedOrBes { get; set; }
        public Nullable<int> BuySellVol { get; set; }
        public Nullable<int> ArzeshAfzudehTax { get; set; }
        public Nullable<int> EnteghaTax { get; set; }
        public Nullable<int> KarmozdMoameleh { get; set; }
    }
}
