//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HooshBartarAccountingApp.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTabaghatHesab
    {
        public int Id { get; set; }
        public string TabagheyehHesab { get; set; }
        public int CodeTabaghehHesab { get; set; }
        public string ZirTzbagheyehHesab { get; set; }
        public int CodeZirtabagheAz { get; set; }
        public int CodeZirtabagheTa { get; set; }
    }
}
